language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  api_key:
    secure: RlKY7nXh0PT9VdJWYGsuFYRZ7fi6sFrDwsQ2pHd0QP7I+UQwsNf8oNnQZtAZGjJxjq/LWVqh0v/VV8acZ1S/yXrTrBbi8lSYXMpQhdI286FSvKZeT2DjvLKv4sJlfHbII/KLXCZ6MBGipGvZCK4KGQHD6MVzn2vAj8vinWfv0CS7HWVjG/f7AM08126cKiYLlZmkTUbmRMSq0R/m7qGQFopJ59cq9/QE+m+ag3aPjlnEP5QSaGR1fVJ9b3GBDsPfxqFDOZgS0rFf+tO9Tu97b+AaHNyncrw40Ge+curhvrhTRHo1M1TCoT/Yz0UpLUVlW8y2A0bRRtoLCfsQB1wOLFgqE8sX1UfL5DEy0BnKB8px1NK4fRSTT/udl7aCxxU7HdfLqsY0Zfe/IQ2UobXK7wrafkqc+uzViOvD53EYmkmQweFhY8LjC/CaiCT8gWLPyBzFzYmO68tVgSqZnx+Np7OXbWJh0tPyyxS31FS7fInywCaty0QISR3HPb4LdTZiV1P17RoKgB16QFWX/OYfGx/wBs4SXjgvFsnYM/8EYbBnUfhtTCHPEGz3eoYLFg6IKrLl+1NIS7lyhuyz4wZ/pCcwIFtZUKMjjU2GjpbNAMEDakaSG77QrVCRorlf5IPwZUoeB0Ro/cQKOr2wEGkUqa82DLBDvVgKqfp6fiWPzns=
cache:
  directories:
  - node_modules
before_script:
  - npm run setup
  - npm run build
script:
  - npm test
