language: node_js
node_js:
    - stable

cache:
    directories:
        - node_modules

before_script:
    - npm run setup
    - npm install codecov -g
    - npm run build

script:
    - npm test

after_success:
    - codecov
    - wget https://raw.githubusercontent.com/Xetera/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL

after_failure:
    - wget https://raw.githubusercontent.com/Xetera/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh failure $WEBHOOK_URL
