language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: KTqTpiioDeGRsDZvm1au5wk3NESUjMJ87bVX59MNIgZf2WNn3E7TxbIN01/GdF9pUnMfxfoAV5TMWlfzze6HnRflWDgSCHQ/mPE3CzY5dHa7/FaeTr8GqCzIkQhWUx2kbUtEM49ENt2AXryNk01WtRJ37ivzNMdwkwuz/lipfJjGWsevQ9eoubl6D5ErubKKpdNlt6GL6CmXVsQFbtmqPzykDzmiBSgqlIkP0R1GIPL5Jq8znbcQ+qdrBrH3KXsG4ftQMqDE+RNBVArQ1/firYPxPuYv7wtKIbXSYwPRCiyXzUL9spa4Xd5dEbcfCdM2AO/MeKXaQhW/BcLOI+GkZwlC7cbJDomj3KJDXcfX2lrVVexpuuoh1n5T0gJnMFkkPbnWaotB5SZg4S2+9d+0s2uV6bsXgRnxPz/LMuxYJ9wWcja2LfEeep9oHRNfnccqJlPUlYO+6+5UJZbl2L0WhKIqUAn1UvQuN1PzTdt0Rbh8Edy1qdMiFepxzHnPQGrin7ms0ABFZhRFJQ7/038neHSMo6nOuQ7Y7xjedi8nnoa52zHzT95uHKqEo95cF9JstAcRW9Ec2bANZuIQdzo330CZyfvkyMnXHvhFHwfmOT+zLcUMfGlBrC+WPJ/GddLg6rk9L2H3KL14AdUF40qbBGTqodVPtmhqxgA6QeVR828=
cache:
  directories:
  - node_modules
before_script:
- npm run setup
- npm run build
script:
- npm test
