version: '3'
services:
  web:
    build: .
    volumes:
    - .:/hifumi
    - /usr/app/node_modules
    links:
    - redis
    environment:
      - ENV=DEVELOPMENT
      - DATABASE_URL=postgres://postgres:@host.docker.internal:5432/discord
      - REDISCLOUD_URL=redis://host.docker.internal:6379
    depends_on:
      - "postgres"
  redis:
    image: redis
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_DB=discord
      - POSTGRES_USER=hifumi
      - POSTGRES_PASSWORD=eagle_jump
volumes:
  logvolume01: {}
